FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt

COPY ./files ./files
COPY ./goodreads_visualizer .

ENV PYTHON_ENV=development

EXPOSE 8501
CMD ["streamlit", "run", "goodreads_visualizer/main.py"]