# fly.toml app configuration file generated for goodreads-visualizer on 2023-08-19T19:14:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "goodreads-visualizer"
primary_region = "atl"

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
