alter table "public"."users" drop constraint "users_external_id_key";

alter table "public"."users" drop constraint "users_pkey";

drop index if exists "public"."users_external_id_key";

drop index if exists "public"."users_pkey";

drop table "public"."users";

create table "public"."users2" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "external_id" bigint not null
);


alter table "public"."users2" enable row level security;

CREATE UNIQUE INDEX users_external_id_key ON public.users2 USING btree (external_id);

CREATE UNIQUE INDEX users_pkey ON public.users2 USING btree (id);

alter table "public"."users2" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."users2" add constraint "users_external_id_key" UNIQUE using index "users_external_id_key";


